### ISSUE TITLE
where is the "train.hdf5" file?

### ISSUE THREAD

**Issue by junliangliu** [bhpfelix/MAC#1]
where can i get "train.hdf5" file from ?

**Comment by bhpfelix** [comment]
Hi,
I used the feature extraction [code](https://github.com/ethanjperez/film/blob/master/scripts/extract_features.py) provided by the official [FiLM](https://github.com/ethanjperez/film) implementation to generate train.hdf5 and val.hdf5 from images. You can download the CLEVR dataset [here](https://cs.stanford.edu/people/jcjohns/clevr/).

**Comment by junliangliu** [comment]
Thanks for your reply! Great work ！
